version: '3.8'
services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    dns:
      - 8.8.8.8
      - 8.8.4.4

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env